dist: xenial

language: c

before_install:
  - sudo apt-get install -y fakeroot gcovr
  - git clone https://github.com/eerimoq/unicorn
  - cd unicorn && make && sudo make install && cd ..
  - wget https://musl.cc/x86_64-linux-musl-cross.tgz
  - tar xf x86_64-linux-musl-cross.tgz
  - source setup.sh
  - env | grep ML_

script:
  - make -C examples/hello_world build
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
