dist: xenial

language: c

before_install:
  - sudo apt-get install -y fakeroot
  - source setup.sh
  - export ML_SOURCES=$ML_ROOT
  - env | grep ML_
  - git clone https://github.com/eerimoq/unicorn
  - cd unicorn && make && sudo make install && cd ..

script:
  - wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.1.3.tar.xz
  - make -C examples/hello_world build
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
